spring.application.name=Roomify
spring.datasource.url=jdbc:mysql://localhost:3306/ROOMIFY_DB
spring.datasource.username=root
spring.datasource.password=1234


# Spring Boot file upload limits
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
server.tomcat.max-swallow-size=50MB
file.upload.dir=uploads

# Firebase Cloud Messaging Configuration
fcm.service-account-file=firebase-service-account.json
fcm.project-id=your-project-id


# For older Spring Boot versions
spring.http.multipart.max-file-size=100MB
spring.http.multipart.max-request-size=100MB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

google.client.id=1041914574744-evaa3p91lu43jr5crr42esqrivkha66m.apps.googleusercontent.com
# JWT Configuration


jwt.secret=mySuperSecretKeyThatIsExactly64CharactersLong123456789012345678901234567890AA

jwt.expiration=86400000

# DevTools settings
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true


# Enable debug logging for security
logging.level.com.ROOMIFY.Roomify=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.authentication=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
