# ===============================
# APP CONFIG
# ===============================
spring.application.name=Roomify
server.port=8080
server.address=0.0.0.0

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/roomify
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
server.tomcat.max-swallow-size=50MB
file.upload.dir=uploads

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=RoomifyJWTSecretKey2026UltraSecureAuthenticationSystemKeyXYZ123456789
jwt.expiration=86400000

# ===============================
# GOOGLE AUTH
# ===============================
google.client.id=1041914574744-evaa3p91lu43jr5crr42esqrivkha66m.apps.googleusercontent.com

# ===============================
# LOGGING
# ===============================
logging.level.com.ROOMIFY.Roomify=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate=INFO